### PR TITLE
Debian package improvements

### PR DESCRIPTION
**Pull request by benley**
* Include init script in the deb
* Let dh-systemd handle things
* Set native package format
* Install default /etc/razer.conf
* Add missing build-depends

### CODE REVIEW

**Comment by mbuesch** [comment]
Build fails with
```
dpkg-checkbuilddeps: Unmet build dependencies: dh-systemd
```

What is missing? Systemd is installed here.

**Comment by benley** [comment]
dh-systemd is just another package you should be able to apt-get install.  It helps with generating postinst/prerm/postrm scripts that install and remove systemd services on systems that use it.

**Comment by mbuesch** [comment]
Ok. Fair enough.
Here's the next error thrown by scripts/makerelease.sh
```
dpkg-source: error: can't build with source format '3.0 (native)': native package version may not have a revision
dpkg-buildpackage: error: dpkg-source -b razercfg-0.32 gave error exit status 255
```
You can also try that yourself. You just need makerelease.lib from here
```
http://bues.ch/gitweb?p=misc.git;a=blob_plain;f=makerelease.lib;hb=HEAD
```
The script basically just runs debuild. (optionally with -uc -us)

**Comment by mjtorn** [comment]
I tested this pull request and solved the issue simply by editing the version in `debian/changelog` to not contain a revision, ie made it read `0.32.1`

**Comment by mbuesch** [comment]
@mjtorn Ok very nice. Could you create a pull request that passes the build script for me to pull. (Just add a commit fixing the issue).

**Comment by benley** [comment]
wow, I completely forgot about this PR, sorry about that. I can push an updated commit in a moment.

**Comment by benley** [comment]
Updated!

**Comment by mjtorn** [comment]
@mbuesch looks like @benley beat me to it. Looks exactly like my changelog edit so :+1: from me.

**Comment by mbuesch** [comment]
Cool, thanks. I'm just wondering whether that .1 in the version serves any purpose. Do we need that, or would version 0.32 (or such) be Ok, too?
As far as I understood it, the number after the dash used to be the Debian increment. Did that notation change?

**Comment by benley** [comment]
Version 0.32 would be fine too - want me to change it?  The number after the dash is still the Debian package revision, but that field isn't used for native packages.

**Comment by mbuesch** [comment]
Thanks for the clarification.
Yes, please remove the .1 then. I'll merge it afterwards (given that makerelease.sh will run).

**Comment by benley** [comment]
OK - updated once again.

**Pull request merged**
