### PR TITLE
Added icon to launcher

### PR DESCRIPTION
**Pull request by thehalftruth**

### CODE REVIEW

**Comment by mbuesch** [comment]
Thanks for the pull request.
Could you please squash that into a single commit?

**Comment by thehalftruth** [comment]
Yes of course, I'll create a new pull request.

**Comment by mbuesch** [comment]
You can also update pull requests. There's no need to create a new one for every change.

**Comment by OvermindDL1** [comment]
For note, when merging through Github you have the option to "Squash and Merge".

Or the person submitting the PR can squash in-place through normal 'git' without needing to create the PR (just have to `git push origin --force` then).

**Comment by mbuesch** [comment]
>For note, when merging through Github you have the option to "Squash and Merge".

There are a couple of reasons I don't do this:
- I don't merge via github directly. That's basically because I want to test things before I push them. (I don't believe in the automated github testing. Especially for hardware related software.)
- People are supposed to work cleanly. High quality software does not arise from crappy commits. Squashing often is not just a matter of putting everything into a single commit (like in this case). It rather is a way to cleanly structure the history and thus make review easy. And proper review is extremely important.

https://bues.ch/r/contribute

**Comment by OvermindDL1** [comment]
True true yep.  Though I'm one of those where I like history in full with development steps so I never squash, though in this case that might have been done anyway.  ^.^

**Pull request closed without merging**
