### PR TITLE
Suggestion for an icon

### PR DESCRIPTION
**Pull request by mjtorn**
So this is the icon you asked me to remove from #56. I think it's a decent one and it's completely free to use, being taken off Wikimedia Commons.

Just for posterity, so we don't forget that an icon would be real nice.

If you have something to add or change in this I'll accomodate, but of course an icon by an actual graphicist would look _even better_ ;)

### CODE REVIEW

**Comment by mbuesch** [comment]
Yes, that looks way better than the initial version.
Can you please rebase this on master, so it only has the "Add icon" commit? That way it's easier to merge; even later (I'm still going to delay this a bit to get some discussion, if people want to discuss the icon).

**Comment by z3ntu** [comment]
@mjtorn Do you know if this icon is available as .svg as the current resolution looks bad (not as tray icon, but if you use this somewhere as a big icon)

**Comment by mbuesch** [comment]
I'd like to second that. An SVG would be a big plus. Everything else can be auto-generated from it.

**Comment by janstuemmel** [comment]
i have a ps and il background. maybe i can design something in the next few days...

**Comment by mjtorn** [comment]
@janstuemmel that would be great! I snatched the base of the logo off of Wikimedia, like I said, but did not edit it in anything but Gimp. Not sure when I'd get around to it, or the other pull request for that matter... And anyone with any experience can do better than I ;)

**Comment by z3ntu** [comment]
I think this is now obsolete? #63

**Comment by mjtorn** [comment]
@z3ntu let's let @mbuesch decide on that, but I like #63. If you have time to tweak it at all that's more time than I got and I honestly care only about having any icon.

**Comment by mbuesch** [comment]
Like I said in the other thread, it's ok to add multiple icons.

One thing we need to sort out is copyright and licenses, though.

If you got parts of the image from somewhere else, please document that.
Also add a text file that includes all copyright notices (including yours) and all licensing information.

**Comment by mjtorn** [comment]
I'm this -><- close to just closing this in favor of #63 - I don't know how to create anything cool with SVGs and I'm sure anyone else will have a better icon. If I have time in the future, I'll just submit something as a new pull request. Despite that, I'll leave this open for just a little while longer.

**Comment by mbuesch** [comment]
>I'm this -><- close to just closing this

Well, it's your pull. Go for it. :)

>I'll just submit something as a new pull request

great.

**Comment by mjtorn** [comment]
Close in favor of #63

**Pull request closed without merging**
