### PR TITLE
new model of deathadder 3500 DPI  RZ01-0163

### PR DESCRIPTION
**Pull request by h0rn3t**
added support new model of deathadder 3500 DPI model RZ01-0163

### CODE REVIEW

**Comment by h0rn3t** [comment]
seems working fine

**Comment by mbuesch** [comment]
Why do you create a new file?
If the protocol is different from an existing one, please explain the differences.

**Comment by mbuesch** [comment]
"deathadder 3500" is not an acceptable name, because we already have that name in the hw_deathadder.c driver.
Also: Do a pull request _after_ you finished your work.

**Comment by h0rn3t** [comment]
@mbuesch  okay

**Comment by h0rn3t** [comment]
@mbuesch some features of chroma version is not supported by 3500DPI version,  "spectrum" mode  for example

**Comment by mbuesch** [comment]
Thanks.
I still prefer this to be in an existing driver, if the differences to the existing driver are not too big.
There's a trade off between creating a new driver and adding conditionals to an existing one.

**Comment by mbuesch** [comment]
see the older hw_deathadder.c for an example. It supports several models that don't differ that much.

**Comment by h0rn3t** [comment]
@mbuesch okay thanks i'll check it

**Pull request closed without merging**
