### PR TITLE
Add support for a newer naga hex

### PR DESCRIPTION
**Pull request by cor3ntin**

### CODE REVIEW

**Comment by mbuesch** [comment]
Thanks a lot for your contribution.

Can you tell us a bit more about how you verified and tested this? Did you look at a USB protocol dump to verify that nothing has changed? Or did you at least check all features whether something broke?
Does the new device have new additional features that we don't support, yet? If so, which ones are that?

Thanks for your help.

**Comment by cor3ntin** [comment]
Hello. 
I don't know how the device compare to a previous naga, but features wise it's really the same as far as I can tell.

Detection works, dpi change works, controls work, leds (wheel + top ) works.
I haven't do serious protocol-level testing, but, from a user perspective it behaves as expected.

**Comment by mbuesch** [comment]
It is pretty unusual that the USB ID is changed without a difference in the protocol.
So I would feel a lot more comfortable, if you could create some USB dumps with the original driver and compare the protocols.

**Comment by mjtorn** [comment]
Probably not worth anything to chime in, but works nicely for me...

**Comment by mbuesch** [comment]
Ok, I'll merge this. But if it turns out to cause any problem, I'll revert it again immediately.
However, I'd still like to get someone looking at the protocols. It's not that hard.

**Pull request merged**
