### PR TITLE
udev: Only rescan if the removed device is from Razer

### PR DESCRIPTION
**Pull request by GrantM11235**
This fixes the first bug that I described in #134

### CODE REVIEW

**Comment by mbuesch** [comment]
Thanks for your pull request.
I'm unsure whether this change is a good idea.
I originally implemented it like this, because it did not work with specific vendor-id. Maybe there was a change in some udev version? This might break for users of older udev, if that is the case.

**Comment by GrantM11235** [comment]
After extensive testing, I have discovered that the original patch doesn't actually work :facepalm:. I'm not sure how I didn't notice this before, I guess I didn't reloaded my udev rules.

When a USB device is removed, `ATTRS{idVendor}` [can't be used](https://unix.stackexchange.com/questions/178341/udev-rule-action-add-is-working-but-action-remove-isnt-working). Luckily, `ENV{PRODUCT}` works and contains the vendor id, so we can use that with a wildcard.

I have tested this with:
- Ubuntu 20.04 with systemd 245
- Debian 10 with systemd 241
- Debian 9 with systemd 232
- Debian 8 with systemd 215

On Debian 8 and 9 the automatic scan runs, but it doesn't detect that the mouse was actually removed until the next time a scan is run, either manually or automatically. This bug is present in the master branch as well.

**Comment by mbuesch** [comment]
Do you plan to do more changes in the near future?
If not, I'm going to release the next version soon, to get the razerd fixes out.

**Comment by GrantM11235** [comment]
I don't have any more changes planned, feel free to release the next version whenever you are ready.

**Comment by mbuesch** [comment]
Great, thanks!

**Pull request merged**
