### PR TITLE
freedesktop icon

### PR DESCRIPTION
**Pull request by janstuemmel**
i made a simple svg icon for razercfg.

Issue: #59

### CODE REVIEW

**Comment by z3ntu** [comment]
I would leave a bit more space between each "circle of snake". Otherwise it looks pretty good!

**Comment by mjtorn** [comment]
+1 for this icon but also +1 for having more space, if it's not a huge hassle

**Comment by mbuesch** [comment]
I like version number 3 and 4.
But I wonder whether we could make a connection to Linux somehow. (Nope, just pasting Tux somewhere in there is not an option. :)
It probably also is a good idea to have multiple icons (just make an icons subdir) and have one "main one" for the desktop file or such.

**Comment by janstuemmel** [comment]
maybe using tux colors for the connection to linux see suggestion 5

**Comment by janstuemmel** [comment]
which do you like, please choose one. then i make one bare snake svg and one freedesktop icon. are you cool with the pr?

**Comment by mjtorn** [comment]
Does anyone know (or have time to look up) what the Freedesktop standard says about multiple icons? My only request with this, related to #58, would be that the default icon or whatever icon goes into a future Debian package is named `razercfg-icon.png`, but if that's a no-go for any reason I'm sure the name can be adapted elsewhere.

**Comment by janstuemmel** [comment]
if you look into `/usr/share/icons/applications/hicolor/scalable/apps/` there are the icons for example in svg, hicolor is the fallback theme for freedesktop distros. so we can put razercfg.svg in this dir and add in the .desktop file `Icon=razercfg`. no need for png files

**Comment by mjtorn** [comment]
I agree that 3 and 4 are the best ones.

Is Tux a requirement, ie. would this compile or run on a BSD? Having Tux there would also make the icon very crowded and in the case of 3 (my favorite) also look like he's going to get eaten :D

For the different coloring options, I'm sure anyone using this would expect a Razer-related program to have the Razer-green color in the icon at least somewhere.

**Comment by mbuesch** [comment]
>Having Tux there 

As I said, pasting tux somewhere in there is not an option.

**Comment by janstuemmel** [comment]
hi, maybe its time to know which icon you prefer, so i can finish this... :)

**Comment by mbuesch** [comment]
Ok, let's simply take #_4 as the main base for the new logo, the lower left from #_5 as a variation and #_3 as a completely different alternative.

**Comment by z3ntu** [comment]
I agree

**Comment by mjtorn** [comment]
@janstuemmel would you mind updating the desktop file stuff and debian/ distribution when you're done? Then the package wouldn't be in an inconsistent state.

Just update the `razercfg.desktop.template` file and add the icons to `debian/qrazercfg.install` - and `uninstall.sh` as well. That's off the top of my head, there might be something more, but I doubt it.

**Comment by janstuemmel** [comment]
ok ill do that. but maybe i will need a few days...

**Comment by janstuemmel** [comment]
i would choose the `razercfg-snake.svg` as tray icon. maybe its good if i upload the the pngs as well. 
the right icon location is the hicolor fallback theme:
* `/usr/share/icons/hicolor/scalable/apps` for svgs 
* `/usr/share/icons/hicolor/SIZExSIZE/apps` for pngs

**Comment by mjtorn** [comment]
It's been a while, so got to ask, is anything happening here?

**Comment by mbuesch** [comment]
I'm actually waiting for an updated pull request.

**Comment by janstuemmel** [comment]
ok i will finish this up, just say me what structure you would like...

**Comment by mbuesch** [comment]
structure?

**Comment by janstuemmel** [comment]
i mean, generate which extension out of the png, where to put them, or just leave the single svg in icons...

**Comment by mbuesch** [comment]
Ah OK.
Well about the place to but this: Just make an icons subdir or such. And then just put the icons in there. I don't care that much about png. They can even be auto-generated on package install, if distributions care.

**Comment by janstuemmel** [comment]
are you ok now with that pr, should i do  a rebase?

**Comment by mbuesch** [comment]
Yes, please rebase and remove all unnecessary commits (see git rebase --interactive)

**Comment by janstuemmel** [comment]
ok, need a few minutes

**Pull request merged**
