### PR TITLE
tray applet

### PR DESCRIPTION
**Pull request by janstuemmel**
maybe a tray applet is a good idea for fast switching profiles.

razercfg-applet

### CODE REVIEW

**Comment by polyzen** [comment]
:+1: Might get me to try out qrazercfg :p

**Comment by mbuesch** [comment]
Cool.
I think one thing we need is hotplug. Even if it's implemented like in qrazercfg via slow polling. So replacing the update-devices button by slow notification polling (see how qrazercfg does it) every second or two would be a good idea.

**Comment by mbuesch** [comment]
Can you reformat the source to use tab indents, please? The rest of the code does it like this, too.
Also polling once a second should be enough. That helps battery life. Yes, qrazercfg does it every 100ms, but qrazercfg is not supposed to run all the time.
Is there any specific reason you override show() to start the timer? If not, please start the timer in __init__() and also make it non-single-shot.

If these things are fixed (and it actually works. I didn't test it, yet), I'd like to merge this.

**Comment by janstuemmel** [comment]
Ok, i'll do it the next few days. But i think it'll be better if we include all ui stuff in a module for pyrazer, then call the ui from pyrazer.ui module, so we can call the the main programm from the applet. i'll make a suggestion...

**Comment by janstuemmel** [comment]
i copied the code from `qrazercfg` to `pyrazer/ui` and added some wrapper methods

**Comment by mbuesch** [comment]
Looks good.
Can you please do a better commit message for the "some improvments" commit, or collapse that commit into some other commit. "some improvements" seems a little bit too generic. :)

The code looks rather good. But I don't really like that we basically have two poll loops now with one being overridden. That seems overly complicated. Often the object oriented approach is good, but sometimes a simple flag is better and makes the code more readable.
Also I don't really like the fact that we rebuild the whole menu structure all the time, even if the data did not change (yes qrazercfg does that, too, but it is not supposed to run all the time).
And I don't see why it's necessary to call razer.rescanMice() from the applet's poll callback. That seems unneeded.
Also there seems to be a lot of commented out code. Remove that unneeded code.

**Comment by janstuemmel** [comment]
ok, i did what you wrote, but i think overriding the poll loops is a good idea. if you start razercfg without the applet you have the normal mainwindow pollloop, else you have the pollloop from the applet, i think thats easy to understand. 

Problem:
if i change the profile in the applet, it gets instantly updateted in mainwindow, but if i change it in the mainwindow, it doesnt gets updated in the applet.

funny fact:
i didnt have a support mouse here, normally i use the deatadder chroma, but this mouse isnt here right now, so i used a razer abyssus and changed the product id in the librazer.c. the protocols must be really similar, because i can set the mouse frequency and the glowing logo led to off/breathing/static. the dpi settings dont work.

**Comment by mbuesch** [comment]
>but if i change it in the mainwindow, it doesnt gets updated in the applet.

Is there a possible fix for that? That seems like a major issue to me.

>icons dont work properly

What does that mean?

>razer abyssus '14 

Cool. :) But don't send a patch to just add the product ID. I don't merge such changes. But feel free to properly reverse engineer the protocol and write/update a driver based on that. Reverse engineering includes capturing the traffic of the original driver.

>i hope to fix the issues obove soon

great. I'll see if I can merge the changes in the mean time. We don't install the tray applet anywhere, yet, so it possibly is OK if it still has issues.

**Comment by janstuemmel** [comment]
> Is there a possible fix for that?

Yes. But it requires to change some logic in the rest of the pyrazer.ui code, you wrote.

> What does that mean?

They aren't shown. Im not very in the freedesktop stuff. I try to figure this out.

> But don't send a patch to just add the product ID.

I won't :). I already played with that, abyssus, windows vm, wireshark, synapse. But i dont get the traffic when i change the dpi on abyssus with synapse. When i change it for deathadder with synapse i get the traffic. wtf?
I also get the traffic for abyssus, when changing led/frequency/profiles, but, as said, not for dpi, that really disapointed me. Any clues on that? should i open an issue?

> I'll see if I can merge the changes in the mean time

cool

**Comment by mbuesch** [comment]
>Any clues on that?

What vm do you use? There are mice (e.g. the original Lachesis) that send/receive invalid USB messages. The Linux kernel userspace USB support used to block most of these, so they don't get into/from the VM.
The only way around this is to use native Windows (or hack the kernel checks).

**Comment by janstuemmel** [comment]
> What vm do you use?

VirtualBox with extension pack and Windows 7.

**Comment by mbuesch** [comment]
Ok, but on the host you use Linux I presume. That means you could be affected by the limitations I described above.

**Pull request merged**
