### PR TITLE
WIP/RFC Freedesktop stuff

### PR DESCRIPTION
**Pull request by mjtorn**
Hi!

I was thinking of how cool it would be if I could run this on my Steam Machine and also test adding non-steam "games" into the Steam UI.

This works on my Debian Stable, but unfortunately it fails on the Steam Machine for two reasons:

  1. PySide is only suggested
  2. PySide is not provided for SteamOS

What do people think is a good solution? Bunding PySide is a possibility, but somewhat annoying.

Maybe it could be re-written in C++, but that's a pretty big undertaking, although SteamOS seems to provide only qt4.

The trendy answer would probably be to make it a Docker container, but I'm not a huge fan and can't be arsed to see if Docker's a possibility on SteamOS.

All that aside, the branch works for me and though IANAL I read up on Razer's brand rules wrt the use of their logo and that should be legit too.

But I'm really hoping to make this somehow usable on an actual gaming machine...

### CODE REVIEW

**Comment by mbuesch** [comment]
>    PySide is only suggested
    PySide is not provided for SteamOS

What about PyQt5? PyQt4 could also work, if it's compiled for the "new" string API (Native str instead of QString in PyQt)

>  I read up on Razer's brand rules wrt the use of their logo and that should be legit too.

I'm not adding a Razer logo. No way. Even if Razer agrees to it. This is not a Razer product.

Adding a desktop file would be ok, though. But it needs to be generated to get the executable path correctly. And it needs to get installed somewhere. Otherwise it's pretty useless.

**Comment by mjtorn** [comment]
> What about PyQt5? PyQt4 could also work, if it's compiled for the "new" string API (Native str instead of QString in PyQt)

There's ridiculously little available on QT on SteamOS, and no Python bindings anywhere.

> I'm not adding a Razer logo. No way. Even if Razer agrees to it. This is not a Razer product.

Ok, do you have a suggestion on what to do? I'm sure it'd be even worse to draw three snakes with Gimp, they'd call it slander :D I can edit the git history on this branch and force-push something new if you like. I'm kind of short on ideas what the icon could be like.

> Adding a desktop file would be ok, though. But it needs to be generated to get the executable path correctly. And it needs to get installed somewhere. Otherwise it's pretty useless.

You're right that I neglected the `make install` scenario. Have to investigate how to slam the paths in there dynamically. CMake is apparently the proper way, as with the other templates.

**Comment by mbuesch** [comment]
> Ok, do you have a suggestion on what to do? I'm sure it'd be even worse to draw three snakes with Gimp,

Well, I'm not against adding a logo in general. It just mustn't look like Razer's. I'm sure some clever designer could come up with something here that doesn't violate rights. Like three snakes in different colours and in a different arrangement.

**Comment by mjtorn** [comment]
What do you think @mbuesch of the logo now?

So I force-pushed a bunch of stuff, but be aware that this does not work. I've never written stuff for CMake, and suddenly I'm seeing this

    CMake Error at cmake_install.cmake:119 (file):
      file INSTALL cannot find
      "/home/mjt/src/git_checkouts/razer/razercfg.desktop".

Despite the `configure_file("razercfg.desktop.template" "razercfg.desktop")` thing in the file.

I didn't have too much time to look into this and frankly lost a bit of interest because of SteamOS' limited package availability. I will fix this up, of course, but it'll be done faster if I'd be told what to write in for CMake or at least a pointer/clue better than the official documentation. AFAICT by the documentation there's nothing wrong with the file.

Thanks!

**Comment by polyzen** [comment]
Looks very phallic.. like a logo for a mexican gay bar :p

**Comment by mbuesch** [comment]
>Looks very phallic

I agree. :)

It's not bad for starters, but I don't like the sharp 90 degree edges and huge heads.

**Comment by mjtorn** [comment]
That's adders (or vipers, not sure how snakes work in English) for ya ;) They're the same kinds of heads the Razer logo has but ... I dunno. A graphicist I am not.

Can we focus on CMake for a while? Could you please see if there's something blatantly obvious sticking out (like ophidian phalli) in the definition files and I can modify the xcf/png later.

Should be safe to pull this branch, I don't intend to force anything more into it, only submit fixes.

**Comment by mbuesch** [comment]
>Can we focus on CMake for a while?

Did you try deleting all temporarily generated cmake files? Often that helps.

**Comment by mjtorn** [comment]
I took a deeper look at this, then.

First I made sure git knows how to clean up after itself, ie `find . -name .gitignore | xargs rm -v`. Removing ignore lists means `git clean` sees _all_ untracked files and can delete them for me.

`cmake .` rendered the desktop file and all others and `make` built it. So this step is still ok.

I ran `git clean -df`, so the tree's clean, and `dpkg-buildpackage -us -uc` gives me other types of errors now as well as the desktop file. This is where it gets fun (<- that's sarcasm).

This is the new stuff, kind of worrysome, but may have flooded by before without me noticing, if it doesn't really affect the package construction and is more benign than it seems:

    Synchronizing state for razerd.service with sysvinit using update-rc.d...
    Executing /usr/sbin/update-rc.d razerd defaults
    insserv: fopen(K01connman): Operation not permitted
    update-rc.d: error: insserv rejected the script header
    *** Error in `systemctl': double free or corruption (fasttop): 0x000055a9541a0af0 ***
    CMake Warning at cmake_install.cmake:101 (message):
      WARNING: systemctl --system enable razerd.service failed: Child aborted

      If you use systemd, enable razerd.service manually

And the old one. why isn't the .desktop file created by dpkg-buildpackage while it is created by running cmake?

    CMake Error at cmake_install.cmake:119 (file):
      file INSTALL cannot find
      "/home/mjt/src/git_checkouts/razer/razercfg.desktop".

Last but not least, to preempt the question "What happens if I don't use the implicit `fakeroot` mechanism but actually `sudo dpkg-buildpackage -us -uc`?"

    Executing /usr/sbin/update-rc.d razerd defaults
    Executing /usr/sbin/update-rc.d razerd enable
    -- systemctl --system enable razerd.service: 0
    CMake Error at cmake_install.cmake:119 (file):
      file INSTALL cannot find
      "/home/mjt/src/git_checkouts/razer/razercfg.desktop".


    Makefile:69: recipe for target 'install' failed

Without any of the permission-denied or memory-management-is-hard type of errors.

**Comment by mjtorn** [comment]
I'd edit the previous message but I don't know how to leave the possibly important details for posterity. If I uninstall the previously-installed razercfg package with `dpkg -P razercfg`, I don't get the `double free or corruption` error anymore.

I do still get the `file INSTALL cannot find ...desktop` error nevertheless, regardless of what I do :(

**Comment by mbuesch** [comment]
Uhm, well. I'm not an expert on debian packages. (That's also why razercfg's debian package is so crappy and I don't provide a binary package). So I guess I can't really help here.

But for cmake I suggest you do the build out of tree. This works fine with cmake and removing all generated files is just a matter of deleting the build directory.

**Comment by mjtorn** [comment]
@mbuesch how does this look now?

PS.
I was thinking of having qrazercfg in its own package that actually depends on pyside. The advantage of that is that I can create (and later make public) a repo of my own with the deps from Debian Stable. Is this in any way interesting to you as a means of release?

I'd probably have to do this for myself anyway, but I'd hate to be stuck with a dead fork, so your ideas on the matter are highly welcomed.

**Comment by mbuesch** [comment]
Looks good. The logo also looks better.
But can we split this up please?
Just do the desktop file, the debian package changes and the logo changes in three separate pull requests.

**Comment by mbuesch** [comment]
The reason is: I don't like to pull everything right now. I'd like to delay the logo a bit.
Also: The history should be cleaned up. Don't add a logo and remove it two commits later. Just redo the original commit.

**Comment by mjtorn** [comment]
That would have been my alternate plan, to simply remove the old icon from the commit history, which I'm fine with. I also squashed some other commits, so sorry for force-pushing to anyone who might have had this branch checked out. Also lost the Darth Vader joke, then ;)

Not sure how to split the desktop and icon files, though, because having a desktop file with no image for the program is ugly, but if you explicitly say that's ok that's what I'll commit.

Also the debian part of this, `debian/install`, must be touched at least for the desktop file to be installed, so did I misunderstand something? I don't think this can really be split into pieces, unless you want the link without an icon...

**Comment by mbuesch** [comment]
>so sorry for force-pushing to anyone who might have had this branch checked out.

That's just fine. It's the usual git workflow.

>because having a desktop file with no image for the program is ugly, but if you explicitly say that's ok that's what I'll commit.

That's OK for the time being. If an icon is eventually added, it will also be added to the desktop file.

>Also the debian part of this, debian/install, must be touched at least for the desktop file to be installed,
Yes, just to _one_ commit adding the desktop file, modifying the cmake and debian files.

Later a commit will be done that adds an icon and modifies desktop file, cmake and debian again.

**Comment by mjtorn** [comment]
> That's just fine. It's the usual git workflow.

For better or worse it often is; fortunately this is a small branch, but I find it annoying to deal with divergent branches in local copies.

>Later a commit will be done that adds an icon and modifies desktop file, cmake and debian again.

As you wish.

**Comment by mjtorn** [comment]
@mbuesch how does this look? It's been hanging for a while now and I think it fits the bill.

**Comment by mbuesch** [comment]
Yes, it looks good. But can you remove the version bump commit, please? That's only done right before a release. And I don't plan a release right now.
Also please add the desktop file to uninstall.sh.
If those two things are done, I'll pull.

**Comment by mjtorn** [comment]
That better now?

**Comment by polyzen** [comment]
:+1:

**Pull request merged**
