### PR TITLE
a razercfg client tool

### PR DESCRIPTION
**Pull request by janstuemmel**
started to build a razercfg client tool. adding more features such as frequency and leds soon.

related to #49 #76 #73

### CODE REVIEW

**Comment by mbuesch** [comment]
We have a client tool. Why do we need a new one? Why don't we extend the existing one?

>related to #49 #76 #73

how is that related?

**Comment by janstuemmel** [comment]
hm, i thought is only possible to change the current resolution with dpimappings. you wrote thats a missing feature...

**Comment by janstuemmel** [comment]
ok, i close this, maybe i integrate this in razercfg

**Comment by mbuesch** [comment]
>hm, i thought is only possible to change the current resolution with dpimappings. you wrote thats a missing feature...

Well, see this: https://github.com/mbuesch/razer/issues/76#issuecomment-229713747

I'm all in favour of implementing that in razercfg and the configuration file (parser).
Feel free to do that and send another pull request, please.

**Comment by z3ntu** [comment]
@mbuesch Do you still develop anything for razercfg? Just interested.

**Comment by mbuesch** [comment]
>Do you still develop anything for razercfg? 

Development of new features is not planned by me. But I'll continue to maintain the project and keep pulling in features and fixes from elsewhere.
The only rule being that the things pulled in have a very high quality.
The occasional bug fix and small maintenance improvement will be done by me from time to time.

That works pretty well, if you look into the history for the last say three years or so. ;)

So if you want a feature, please develop it and make sure it's well designed. Then it's guaranteed to be pulled in.

**Comment by mbuesch** [comment]
That reminds me I should do a release. There's quite some stuff stacking up in git that's not in a release, yet.

**Pull request closed without merging**
